spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: ecommerce
    password: ecommerce123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret: ZGV2U2VjcmV0S2V5Rm9yRWNvbW1lcmNlTWljcm9zZXJ2aWNlMjAyNERldmVsb3BtZW50T25seQ==
