spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: ecommerce
    password: ecommerce123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: rabbitmq
